server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
        mail:
            smtp:
              ssl:
                trust: "*"
              auth: true
            starttls:
                enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000

